//localhost
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/650e332fa43c4453bd52cf55
###
GET http://localhost:8080/contacts/650e332fa43c4453bd52cf56
###
GET http://localhost:8080/contacts/650e332fa43c4453bd52cf57
###
GET http://localhost:8080/contacts/650e332fa43c4453bd52cf58

//Production deploy
###
GET https://cse341-projects-tefx.onrender.com/contacts
###
GET https://cse341-projects-tefx.onrender.com/contacts/650e332fa43c4453bd52cf55
###
GET https://cse341-projects-tefx.onrender.com/contacts/650e332fa43c4453bd52cf56
###
GET https://cse341-projects-tefx.onrender.com/contacts/650e332fa43c4453bd52cf57
###
GET https://cse341-projects-tefx.onrender.com/contacts/650e332fa43c4453bd52cf58