//localhost
### Get all contacts from the collection
GET http://localhost:8080/contacts

### Get a contact by id
GET http://localhost:8080/contacts/650e332fa43c4453bd52cf56

### Create a new contact in the collection
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Calypso",
    "lastName": "Aurich",
    "email": "calypso@email.com",
    "favoriteColor": "grey",
    "birthday": "April 15"
}

### Update a contact in the collection by id
PUT http://localhost:8080/contacts/6514e55bb764717f0503e51e HTTP/1.1
Content-Type: application/json

{
    "firstName":"Calypso",
    "lastName":"Aurich",
    "email":"calypsoBites@email.com",
    "favoriteColor":"greyish",
    "birthday":"May 15"
}

### Delete a contact in the collection by id
DELETE http://localhost:8080/contacts/6514e55bb764717f0503e51e HTTP/1.1



//Production deploy
### Get all contacts from the collection
GET https://cse341-projects-tefx.onrender.com/contacts

###### Get a contact by id
GET https://cse341-projects-tefx.onrender.com/contacts/650e332fa43c4453bd52cf55

### Create a new contact in the collection
POST https://cse341-projects-tefx.onrender.com/contacts/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Calypso",
    "lastName": "Aurich",
    "email": "calypso@email.com",
    "favoriteColor": "grey",
    "birthday": "April 15"
}

### Update a contact in the collection by id
PUT https://cse341-projects-tefx.onrender.com/contacts/6514a4bbc06a86e0b3c49e19 HTTP/1.1
Content-Type: application/json

{
    "firstName":"Calypso",
    "lastName":"Aurich",
    "email":"calypsoBites@email.com",
    "favoriteColor":"greyish",
    "birthday":"May 15"
}

### Delete a contact in the collection by id
DELETE https://cse341-projects-tefx.onrender.com/contacts/6514a4bbc06a86e0b3c49e19 HTTP/1.1